from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

all_surah = ReplyKeyboardMarkup(resize_keyboard=True)
btn1 = KeyboardButton(text='Сура ~ 1')
btn2 = KeyboardButton(text='Сура ~ 2')
btn3 = KeyboardButton(text='Сура ~ 3')
btn4 = KeyboardButton(text='Сура ~ 4')
btn5 = KeyboardButton(text='Сура ~ 5')
btn6 = KeyboardButton(text='Сура ~ 6')
btn7 = KeyboardButton(text='Сура ~ 7')
btn8 = KeyboardButton(text='Сура ~ 8')
btn9 = KeyboardButton(text='Сура ~ 9')
btn10 = KeyboardButton(text='Сура ~ 10')
btn11 = KeyboardButton(text='Сура ~ 11')
btn12 = KeyboardButton(text='Сура ~ 12')
btn13 = KeyboardButton(text='Сура ~ 13')
btn14 = KeyboardButton(text='Сура ~ 14')
btn15 = KeyboardButton(text='Сура ~ 15')
btn16 = KeyboardButton(text='Сура ~ 16')
btn17 = KeyboardButton(text='Сура ~ 17')
btn18 = KeyboardButton(text='Сура ~ 18')
btn19 = KeyboardButton(text='Сура ~ 19')
btn20 = KeyboardButton(text='Сура ~ 20')
btn21 = KeyboardButton(text='Сура ~ 21')
btn22 = KeyboardButton(text='Сура ~ 22')
btn23 = KeyboardButton(text='Сура ~ 23')
btn24 = KeyboardButton(text='Сура ~ 24')
btn25 = KeyboardButton(text='Сура ~ 25')
btn26 = KeyboardButton(text='Сура ~ 26')
btn27 = KeyboardButton(text='Сура ~ 27')
btn28 = KeyboardButton(text='Сура ~ 28')
btn29 = KeyboardButton(text='Сура ~ 29')
btn30 = KeyboardButton(text='Сура ~ 30')
btn31 = KeyboardButton(text='<= Выбрать Дуа =>')

all_surah.row(btn1, btn2, btn3)
all_surah.row(btn4, btn5, btn6)
all_surah.row(btn7, btn8, btn9)
all_surah.row(btn10, btn11, btn12)
all_surah.row(btn13, btn14, btn15)
all_surah.row(btn16, btn17, btn18)
all_surah.row(btn19, btn20, btn21)
all_surah.row(btn22, btn23, btn24)
all_surah.row(btn25, btn26, btn27)
all_surah.row(btn28, btn29, btn30)
all_surah.add(btn31)
